---
- hosts: all
  become: yes
  become_method: sudo
  vars_files:
    - vars/all.yml
  roles:
    - MWojtowicz.devbox
  tasks:
    - name: "Create /var/cms directory"
      file:
        path: /var/cms
        state: directory
        mode: 0775
        owner: apache
        group: apache

    - name: "Set /var/cms facl"
      command: setfacl -R -m u:"apache":rwX -m u:vagrant:rwX /var/cms
      args:
        chdir: /

    - name: "Set /var/cms facl"
      command: setfacl -dR -m u:"apache":rwX -m u:vagrant:rwX /var/cms
      args:
        chdir: /

    - name: "nginx vHosts"
      template:
          src: "{{ item }}"
          dest: /etc/nginx/conf.d/
          owner: nginx
          group: nginx
          mode: 0644
          backup: yes
      with_fileglob:
        - nginx/vhosts/*
      notify: reload nginx
