---

- name: "Install app vhosts"
  template: src="files/vhosts/{{item}}.j2" dest="/etc/apache2/sites-available/{{item}}.conf"
  with_items:
    - logs
    - mailhog

- name: "Install app vhosts"
  command: /usr/sbin/a2ensite {{item}} creates=/etc/apache2/sites-enabled/{{item}}.conf
  with_items:
    - logs
    - mailhog
  notify: restart apache

- name: "Check if CMS project has been cloned"
  stat: path=/var/www/cms
  register: cms

- include: task.cms.yml
  when: cms.stat.exists

- name: "Pimpmylog config"
  template: src={{ item }} dest="/var/www/pimpmylog/config.user.php"
  with_fileglob:
    - files/pimpmylogs.j2