---
- name: Install putty
  yum: name=putty state=latest
  when: ansible_os_family == 'RedHat'

- name: Install putty
  apt: name=putty state=latest
  when: ansible_os_family == 'Debian'

- name: Convert OpenSSH key to PPK format
  command: puttygen private_key -O private -o private_key.ppk
  args:
    chdir: /vagrant/.vagrant/machines/default/virtualbox