---

- name: "Download Git prompt"
  get_url:
    url: https://github.com/jimeh/git-aware-prompt/archive/master.zip
    dest: /root/gitprompt.zip
  register: gitprompt_download
  when: gitprompt_install

- name: "Install Git prompt"
  unarchive: src=/root/gitprompt.zip dest=/etc
  when: gitprompt_download.changed
  register: gitprompt

- name: "Install Git prompt in .bashrc"
  blockinfile:
    dest: "{{ item }}"
    create: yes
    block: |
      export GITAWAREPROMPT=/etc/git-aware-prompt-master
      source "${GITAWAREPROMPT}/main.sh"
  with_items:
   - /root/.bashrc
   - /vagrant/.bashrc
  when: gitprompt.changed